Repository lethalgem/godot-wild-jam-81, pull requests merged in 2025-05, with the labels that each got.

#22 Player Input Setup & Camera Movement
  assets/textures/prototype_surface_1.png
  assets/textures/prototype_surface_1.png.import
  assets/textures/prototype_surface_2.png
  assets/textures/prototype_surface_2.png.import
  materials/prototype_surface.tres
  project.godot
  scenes/movement_test.tscn
  scenes/player_3d.tscn
  scripts/player_3d.gd
  scripts/player_3d.gd.uid
  scripts/player_cam.gd
  scripts/player_cam.gd.uid
Labels: gameplay mechanic

#26 Show and hide mouse when `esc` is pressed
  scripts/player_cam.gd
Labels: gameplay mechanic

#27 Flash Light + Battery Life
  scenes/player_3d.tscn
  scripts/player_cam.gd
Labels: gameplay mechanic

#29 Chapo the goat/20
  project.godot
  scenes/lighting_test.tscn
  scenes/lightning_manager.tscn
  scenes/main_game.tscn
  scenes/player_3d.tscn
  scenes/setting_menu.tscn
  scripts/audio_slider.gd
  scripts/audio_slider.gd.uid
  scripts/lightning_manager.gd
  scripts/lightning_manager.gd.uid
  scripts/main_game.gd
  scripts/main_game.gd.uid
  scripts/setting_menu.gd
  scripts/setting_menu.gd.uid
  scripts/setting_menu_canva.gd
  scripts/setting_menu_canva.gd.uid
  themes/audio_menu_labels.tres
  themes/default_bus_layout.tres
Labels: gameplay mechanic

#32 Lightning Manager Update
  environments/modifiable.tres
  scenes/lighting_test.tscn
  scenes/lightning_manager.tscn
  scripts/lightning_manager.gd
Labels: polish

#30 Eng Game Screen and Menus
  project.godot
  scenes/battery.tscn
  scenes/end_game_screen.tscn
  scenes/main_game.tscn
  scenes/main_game.tscn11874079198.tmp
  scenes/main_game.tscn12002864379.tmp
  scenes/player_3d.tscn
  scripts/battery.gd
  scripts/battery.gd.uid
  scripts/end_game_screen.gd
  scripts/end_game_screen.gd.uid
  scripts/main_game.gd
  scripts/player_cam.gd
  scripts/setting_menu.gd
  scripts/setting_menu_canva.gd
  themes/default_bus_layout.tres
  themes/game_over_title.tres
Labels: gameplay mechanic

#35 battery update, death planes and finish line
  environments/placeholder_sky.tres
  scenes/lighting_test.tscn
  scenes/main_game.tscn
  scenes/mountain_test_3.tscn
  scripts/end_game_screen.gd
  scripts/main_game.gd
  scripts/player_cam.gd
Labels: gameplay mechanic

#38 Lethalgem estuped
  scripts/player_cam.gd
Labels: bug

#39 Add footstep sounds
  assets/sfx/Footsteps/Gravel_Walking__01.wav
  assets/sfx/Footsteps/Gravel_Walking__01.wav.import
  assets/sfx/Footsteps/Gravel_Walking__02.wav
  assets/sfx/Footsteps/Gravel_Walking__02.wav.import
  assets/sfx/Footsteps/Gravel_Walking__03.wav
  assets/sfx/Footsteps/Gravel_Walking__03.wav.import
  assets/sfx/Footsteps/Gravel_Walking__04.wav
  assets/sfx/Footsteps/Gravel_Walking__04.wav.import
  assets/sfx/Footsteps/Gravel_Walking__05.wav
  assets/sfx/Footsteps/Gravel_Walking__05.wav.import
  assets/sfx/Footsteps/Gravel_Walking__06.wav
  assets/sfx/Footsteps/Gravel_Walking__06.wav.import
  assets/sfx/Footsteps/Gravel_Walking__07.wav
  assets/sfx/Footsteps/Gravel_Walking__07.wav.import
  assets/sfx/Footsteps/Gravel_Walking__08.wav
  assets/sfx/Footsteps/Gravel_Walking__08.wav.import
  assets/sfx/Footsteps/Gravel_Walking__09.wav
  assets/sfx/Footsteps/Gravel_Walking__09.wav.import
  assets/sfx/Footsteps/Gravel_Walking__10.wav
  assets/sfx/Footsteps/Gravel_Walking__10.wav.import
  assets/sfx/Footsteps/Gravel_Walking__11.wav
  assets/sfx/Footsteps/Gravel_Walking__11.wav.import
  assets/sfx/Footsteps/Gravel_Walking__12.wav
  assets/sfx/Footsteps/Gravel_Walking__12.wav.import
  assets/sfx/Footsteps/Gravel_Walking__13.wav
  assets/sfx/Footsteps/Gravel_Walking__13.wav.import
  assets/sfx/Footsteps/Gravel_Walking__14.wav
  assets/sfx/Footsteps/Gravel_Walking__14.wav.import
  assets/sfx/Footsteps/Gravel_Walking__15.wav
  assets/sfx/Footsteps/Gravel_Walking__15.wav.import
  assets/sfx/Footsteps/Gravel_Walking__16.wav
  assets/sfx/Footsteps/Gravel_Walking__16.wav.import
  assets/sfx/Footsteps/Gravel_Walking__17.wav
  assets/sfx/Footsteps/Gravel_Walking__17.wav.import
  assets/sfx/Footsteps/Gravel_Walking__18.wav
  assets/sfx/Footsteps/Gravel_Walking__18.wav.import
  assets/sfx/Footsteps/Gravel_Walking__19.wav
  assets/sfx/Footsteps/Gravel_Walking__19.wav.import
  assets/sfx/Footsteps/Gravel_Walking__20.wav
  assets/sfx/Footsteps/Gravel_Walking__20.wav.import
  scenes/player_3d.tscn
  scripts/lightning_manager.gd
  scripts/player_3d.gd
Labels: gameplay mechanic

#44 Pinned Battery Indicator Bottom Left
  scenes/player_3d.tscn
Labels: polish

#46 Fixed Font and Edited Game Over Text
  assets/fonts/Juvanze-ovw9A.otf
  assets/fonts/Juvanze-ovw9A.otf.import
  scenes/end_game_screen.tscn
  scenes/setting_menu.tscn
  themes/audio_menu_labels.tres
Labels: polish

#47 Darken environment
  assets/glow/GlowMask.png.import
  assets/glow/GlowSprite.png.import
  assets/models/flashlight_0.png.import
  assets/models/flashlight_1.png.import
  assets/models/flashlight_10.png.import
  assets/models/flashlight_11.png.import
  assets/models/flashlight_12.png.import
  assets/models/flashlight_13.png.import
  assets/models/flashlight_14.png.import
  assets/models/flashlight_15.png.import
  assets/models/flashlight_16.png.import
  assets/models/flashlight_17.png.import
  assets/models/flashlight_2.png.import
  assets/models/flashlight_3.png.import
  assets/models/flashlight_4.png.import
  assets/models/flashlight_5.png.import
  assets/models/flashlight_6.png.import
  assets/models/flashlight_7.png.import
  assets/models/flashlight_8.png.import
  assets/models/flashlight_9.png.import
  assets/models/object_Deck_basecolor.png.import
  assets/models/object_Deck_normal.png.import
  assets/models/object_Deck_roughness.png.import
  assets/models/object_Metal A_basecolor.png.import
  assets/models/object_Metal A_metallic-Metal A_roughness.png.import
  assets/models/object_Metal A_normal.png.import
  assets/models/object_Port_basecolor.png.import
  assets/models/object_Port_metallic-Port_roughness.png.import
  assets/models/object_Port_normal.png.import
  assets/textures/prototype_surface_1.png.import
  assets/textures/prototype_surface_2.png.import
  environments/lightning_env.tres
  icon.png.import
  project.godot
  scenes/lightning_manager.tscn
  scenes/main_game.tscn
  scenes/mountain_test_3.tscn
  scenes/player_3d.tscn
  scenes/setting_menu.tscn
  scenes/terrain003.tscn
  scripts/lightning_manager.gd
  scripts/player_cam.gd
  skies/black_sky.tres
  terrain_003/terrain3d_00-07.res
  themes/default_bus_layout.tres
Labels: polish

#48 Final changes before release
  assets/branding/splash_screen.png
  assets/branding/splash_screen.png.import
  icon.png
  icon.png.import
  project.godot
  scenes/lightning_manager.tscn
  scripts/lightning_manager.gd
Labels: polish
